Version number update to see if installation problem can be fixed.
A user reported the error "conftest.c:10:28: error: ac_nonexistent.h: No such file or directory". I want to see if it will go away just from a simple clean and re-export.